### ISSUE TITLE
new event   'regionentrance': 'Region Entrance',     'regionexiting': 'Region Exiting'", 

### ISSUE THREAD

**Issue by wzpyh** [mezz64/pyHik#35]
there are two new smart event in hikvision platform , please update contrants.py ,thanks.

    'regionentrance': 'Region Entrance',
    'regionexiting': 'Region Exiting'

**Comment by wzpyh** [comment]
that is quick .. LOL

**Comment by wzpyh** [comment]
in 0.2.1, these two sensor names should all lower case

**Comment by mezz64** [comment]
Fixed in 0.2.2.
