### ISSUE TITLE
Unable to get motion events from Hikvision doorbell camera

### ISSUE THREAD

**Issue by ptdalen** [mezz64/pyHik#37]
I have 4 POE cameras, and one wireless camera (Doorbell Camera)  I believe the model is DS-KB6003-WIP.  There are a lot of rebranded versions of this camera.  I am unable to get motion events from the doorbell camera, but have no issues with getting motion events from my POE cameras.  All Cameras are connected to my NVR.  

The only difference in my config between the NVR and the doorbell cameras is that I use the NVR IP and high ports for the events (65002, 03, etc).  For the wireless doorbell camera I dont have that option.

I'm connecting with port 80, username and password.

I'm using the most current version on Home Assistant (87.1), but it has never worked for me.  

Edit:  I forgot to add that the binary sensor does get created, it just never reports motion.  The camera does have the notify survelnce center checked

**Comment by mezz64** [comment]
I'm afraid others have found that the doorbell devices (see closed issue #16) do not have a proper alertStream endpoint and as a result don't work with this library.

It may just be a matter of adding workaround for some new api quirks, but I don't believe anyone has been able to find any documentation.
