### ISSUE TITLE
HA Switch

### ISSUE THREAD

**Issue by dgomes** [mezz64/pyHik#61]
Sorry for probably being offtopic

Have you considered merging hikvision and hikvisioncam in HA ?

**Comment by mezz64** [comment]
It's something that I had planned to do at one point, but just never found the time.  The motion on/off functionality does already exist within pyhik.

Unfortunately, it's not something I see myself getting to anytime soon.

**Comment by dgomes** [comment]
OK, I too don't have much time in hands but I'm missing "Smart Events" such as "Intrusion Detection" and "Line Crossing".

I suppose it would be better to have them through hikvision than to continue support hikvisioncam.

I might come back to this issue with a link to a PR ;)
